import { StatusBar } from 'expo-status-bar';
import { LinearGradient } from 'expo-linear-gradient';
import * as Haptics from 'expo-haptics';
import * as Clipboard from 'expo-clipboard';
import NetInfo from '@react-native-community/netinfo';
import { Ionicons } from '@expo/vector-icons';
import { useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator, AppState, KeyboardAvoidingView, Linking, Platform,
  Pressable, SafeAreaView, ScrollView, Share, StyleSheet, Switch, Text, TextInput, View,
} from 'react-native';
import { activityCopy, distanceText, primaryMetricText } from './src/domain/activity';
import { ROUTE_POINTS, toApiPoint } from './src/domain/route';
import { ActivitySetupScreen, type ActivitySetupValue, type SetupMode } from './src/features/activity/ActivitySetupScreen';
import { LiveActivityScreen } from './src/features/activity/LiveActivityScreen';
import { locationPermissionStatus, stopBackgroundTracking } from './src/locationTracking';
import { formatDuration } from './src/rideUtils';
import { activityService, ApiError, type ActivitySummary, type ApiGroup, type ApiMember } from './src/services/activityService';
import { storage, type Profile } from './src/storage';
import { authService, type AuthUser } from './src/services/authService';
import { Button } from './src/ui/Button';
import { ConfirmDialog } from './src/ui/ConfirmDialog';
import { colors as C } from './src/ui/theme';

// Local previews can exercise the ride flow without weakening production auth.
// Expo replaces __DEV__ at build time, so production bundles can never enable this path.
const localDemoMode = __DEV__ && process.env.EXPO_PUBLIC_DEMO_MODE === 'true';
const localDemoUser: AuthUser = {
  id: 'local-demo-user',
  email: 'demo@paladin.local',
  user_metadata: { display_name: 'Demo Rider' },
  app_metadata: { provider: 'local' },
  aud: 'authenticated',
  created_at: '1970-01-01T00:00:00.000Z',
};

type Screen = 'boot' | 'configuration' | 'onboarding' | 'auth' | 'passwordReset' | 'home' | 'setup' | 'lobby' | 'active' | 'summary' | 'settings' | 'history';
type Mode = SetupMode;
const EMPTY_PROFILE: Profile = { deviceId: '', displayName: '', voiceEnabled: false, units: 'metric', demoMode: false };

function Header({ title, onBack, right }: { title: string; onBack?: () => void; right?: React.ReactNode }) {
  return <View style={s.header}>{onBack ? <Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={onBack} style={s.iconButton}><Ionicons name="arrow-back" size={21} color={C.ink} /></Pressable> : <Logo />}
    <Text style={s.headerTitle}>{title}</Text>{right || <View style={{ width: 42 }} />}</View>;
}

function Logo() { return <View style={s.logo}><View style={s.logoMark}><View style={s.logoDot} /><View style={s.logoTrail} /></View><Text style={s.logoText}>PALADIN</Text></View>; }
function Initials({ member, size = 44 }: { member: Pick<ApiMember, 'initials' | 'color'>; size?: number }) { return <View style={[s.avatar, { width: size, height: size, borderRadius: size / 2, backgroundColor: member.color }]}><Text style={s.avatarText}>{member.initials}</Text></View>; }
function Onboarding({ onDone }: { onDone: () => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  return <LinearGradient colors={[C.cream, '#E5F1E6']} style={s.fill}><SafeAreaView style={s.onboarding}><Logo /><View style={s.onboardHero}><View style={s.onboardIcon}><Ionicons name="people-circle-outline" size={54} color={C.ink} /></View><Text style={s.kicker}>WELCOME TO PALADIN</Text><Text style={s.bigTitle}>Move together.\nMeet again.</Text><Text style={s.body}>A private live map for running and cycling groups, with quick check-ins and a double-blind way to find your kaki again.</Text><View style={s.onboardPrivacy}><Ionicons name="shield-checkmark-outline" size={22} color={C.ink} /><Text style={s.onboardPrivacyText}>You choose hidden, approximate, or precise location for every activity. We ask only when your group starts.</Text></View></View><Button disabled={busy} label={busy ? 'Opening…' : 'Open Paladin'} icon="arrow-forward" onPress={async () => { setBusy(true); await onDone(); }} /></SafeAreaView></LinearGradient>;
}

function AuthScreen({ onAuthenticated }: { onAuthenticated: (user: AuthUser) => Promise<void> }) {
  const [create, setCreate] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const valid = email.includes('@') && password.length >= 8 && (!create || name.trim().length >= 2);
  const submitAuth = async () => { if (!valid || busy) return; setBusy(true); setError(''); setMessage(''); try { const result = create ? await authService.signUp(email, password, name) : await authService.signIn(email, password); if (result.session && result.user) await onAuthenticated(result.user); else if (create) setMessage('Check your email to confirm your account, then sign in.'); } catch (e) { setError(e instanceof Error ? e.message : 'Authentication failed. Please try again.'); } finally { setBusy(false); } };
  return <LinearGradient colors={[C.cream, '#E8F2E6']} style={s.fill}><SafeAreaView style={s.fill}><KeyboardAvoidingView style={s.authWrap} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Logo /><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.authContent}><Text style={s.kicker}>{create ? 'CREATE YOUR ACCOUNT' : 'WELCOME BACK'}</Text><Text style={s.bigTitle}>{create ? 'Join the group.' : 'Move together.'}</Text><Text style={s.body}>Your account keeps active runs, rides, profile settings, and history available across devices.</Text>{create ? <Field label="DISPLAY NAME"><TextInput value={name} onChangeText={setName} autoCapitalize="words" placeholder="Your display name" placeholderTextColor="#97A59F" style={s.input} /></Field> : null}<Field label="EMAIL"><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email" placeholder="you@example.com" placeholderTextColor="#97A59F" style={s.input} /></Field><Field label="PASSWORD"><TextInput value={password} onChangeText={setPassword} secureTextEntry autoComplete={create ? 'new-password' : 'current-password'} placeholder="At least 8 characters" placeholderTextColor="#97A59F" style={s.input} /></Field>{error ? <View style={s.error}><Ionicons name="alert-circle" size={19} color={C.red} /><Text style={s.errorText}>{error}</Text></View> : null}{message ? <View style={[s.error, { backgroundColor: '#E5F3C1' }]}><Ionicons name="checkmark-circle" size={19} color={C.ink} /><Text style={[s.errorText, { color: C.ink }]}>{message}</Text></View> : null}<View style={{ marginTop: 24, gap: 10 }}><Button label={busy ? 'Please wait…' : create ? 'Create Account' : 'Sign In'} disabled={!valid || busy} onPress={submitAuth} /><Button label={create ? 'I already have an account' : 'Create an account'} secondary onPress={() => { setCreate(!create); setError(''); setMessage(''); }} />{!create ? <Pressable onPress={async () => { if (!email.includes('@')) return setError('Enter your email first.'); try { await authService.resetPassword(email); setMessage('Password reset instructions were sent to your email.'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not send reset email.'); } }}><Text style={s.skip}>Forgot password?</Text></Pressable> : null}</View></ScrollView></KeyboardAvoidingView></SafeAreaView></LinearGradient>;
}

function ConfigurationScreen() { return <SafeAreaView style={s.screen}><View style={[s.content, { flex: 1, justifyContent: 'center' }]}><Logo /><View style={[s.onboardIcon, { marginTop: 38 }]}><Ionicons name="cloud-offline-outline" size={48} color={C.ink} /></View><Text style={s.kicker}>PUBLIC SERVICE SETUP REQUIRED</Text><Text style={s.bigTitle}>Connect Paladin.</Text><Text style={s.body}>Add the Supabase project URL and publishable key to the app environment, then restart Paladin. Setup instructions are included in README.md.</Text></View></SafeAreaView>; }

function PasswordReset({ onDone }: { onDone: () => void }) { const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const valid = password.length >= 8 && password === confirm; return <SafeAreaView style={s.screen}><KeyboardAvoidingView style={s.authWrap} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Logo /><View style={s.authContent}><Text style={s.kicker}>SECURE YOUR ACCOUNT</Text><Text style={s.bigTitle}>Choose a new password.</Text><Text style={s.body}>Use at least eight characters and avoid passwords you use elsewhere.</Text><Field label="NEW PASSWORD"><TextInput value={password} onChangeText={setPassword} secureTextEntry style={s.input} placeholder="At least 8 characters" /></Field><Field label="CONFIRM PASSWORD"><TextInput value={confirm} onChangeText={setConfirm} secureTextEntry style={s.input} placeholder="Enter it again" /></Field>{error ? <View style={s.error}><Text style={s.errorText}>{error}</Text></View> : null}<View style={{ marginTop: 24 }}><Button label={busy ? 'Updating…' : 'Update Password'} disabled={!valid || busy} onPress={async () => { setBusy(true); setError(''); try { await authService.updatePassword(password); onDone(); } catch (e) { setError(e instanceof Error ? e.message : 'Password could not be updated.'); } finally { setBusy(false); } }} /></View></View></KeyboardAvoidingView></SafeAreaView>; }

function Home({ profile, active, history, onCreate, onJoin, onResume, onSettings, onHistory, onOpenRide }: { profile: Profile; active: ApiGroup | null; history: ActivitySummary[]; onCreate: () => void; onJoin: () => void; onResume: () => void; onSettings: () => void; onHistory: () => void; onOpenRide: (ride: ActivitySummary) => void }) {
  const kaki = [...new Map(history.flatMap((activity) => {
    const viewerId = activity.viewerParticipantId;
    if (!viewerId) return [];
    return (activity.connections || []).filter((pair) => pair.split(':').includes(viewerId)).flatMap((pair) => {
      const otherId = pair.split(':').find((id) => id !== viewerId);
      const person = activity.riders.find((rider) => rider.id === otherId);
      return person ? [[person.id, { person, activity }]] as const : [];
    });
  })).values()];
  return <LinearGradient colors={[C.cream, '#E8F2E6']} style={s.fill}><SafeAreaView style={s.fill}><ScrollView contentContainerStyle={s.home}>
    <View style={s.homeHeader}><Logo /><Pressable accessibilityRole="button" accessibilityLabel="Settings" onPress={onSettings} style={s.iconButton}><Ionicons name="settings-outline" size={21} color={C.ink} /></Pressable></View>
    <View><Text style={s.kicker}>{profile.displayName ? `WELCOME BACK, ${profile.displayName.toUpperCase()}` : 'YOUR PRIVATE ACTIVITY GROUP'}</Text><Text style={s.heroTitle}>Move with your <Text style={{ color: C.orange, fontStyle: 'italic' }}>kaki.</Text></Text><Text style={s.body}>Run or ride on one private map, check in without typing, and reconnect only when the feeling is mutual.</Text></View>
    {active ? <View style={s.activeCard}><View style={s.activeIcon}><Ionicons name={activityCopy(active.activity).icon} size={25} color={C.white} /></View><View style={{ flex: 1 }}><Text style={s.kicker}>ACTIVE {activityCopy(active.activity).noun.toUpperCase()} · {active.code}</Text><Text style={s.cardTitle}>{active.start.name} → {active.destination.name}</Text><Text style={s.meta}>{active.members.length} {active.members.length === 1 ? activityCopy(active.activity).participant : activityCopy(active.activity).participants} connected</Text></View><Ionicons name="chevron-forward" size={20} color={C.ink} /></View> : null}
    <View style={{ gap: 11 }}>{active ? <Button label={`Resume ${activityCopy(active.activity).noun}`} icon="navigate" onPress={onResume} /> : <Button label="Create Activity" icon="add" onPress={onCreate} />}<Button label="Join Group" icon="keypad-outline" secondary onPress={onJoin} /></View>
    {kaki.length ? <View><View style={s.sectionHead}><Text style={s.sectionTitle}>YOUR KAKI</Text><Text style={s.meta}>Mutual only</Text></View>{kaki.slice(0, 3).map(({ person, activity }) => <Pressable accessibilityRole="button" key={person.id} onPress={onCreate} style={s.kakiRow}><Initials member={person as ApiMember} size={42} /><View style={{ flex: 1 }}><Text style={s.memberName}>{person.name}</Text><Text style={s.meta}>Met on a {activityCopy(activity.activity || 'ride').noun} · plan another</Text></View><Ionicons name="add-circle-outline" size={21} color={C.orange} /></Pressable>)}</View> : null}
    <View><View style={s.sectionHead}><Text style={s.sectionTitle}>RECENT ACTIVITIES</Text>{history.length ? <Pressable accessibilityRole="button" onPress={onHistory}><Text style={s.link}>View all</Text></Pressable> : null}</View>{history.length ? history.slice(0, 2).map((ride) => <SummaryRow key={ride.code} units={profile.units} ride={ride} onPress={() => onOpenRide(ride)} />) : <View style={s.empty}><Ionicons name="trail-sign-outline" size={30} color={C.soft} /><Text style={s.emptyTitle}>No activities yet</Text><Text style={s.meta}>Create a group and get moving.</Text></View>}</View>
  </ScrollView></SafeAreaView></LinearGradient>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <View style={{ marginTop: 26 }}><Text style={s.fieldLabel}>{label}</Text>{children}</View>; }

function Lobby({ group, participantId, busy, error, onStart, onLeave, onChangeDestination, onRemove }: { group: ApiGroup; participantId: string; busy: boolean; error: string; onStart: () => void; onLeave: () => void; onChangeDestination: () => void; onRemove: (id: string) => void }) {
  const host = group.hostId === participantId;
  const copy = activityCopy(group.activity);
  const [confirmLeave, setConfirmLeave] = useState(false);
  const [removeId, setRemoveId] = useState('');
  const removeName = group.members.find((member) => member.id === removeId)?.name || 'this participant';
  const share = () => Share.share({ message: `Join my Paladin ${copy.noun} from ${group.start.name} to ${group.destination.name}. Group code: ${group.code}` });
  return <SafeAreaView style={s.screen}><Header title="GROUP LOBBY" onBack={() => setConfirmLeave(true)} /><ScrollView contentContainerStyle={s.content}>
    <View style={s.codeCard}><Text style={s.codeEyebrow}>SHARE THIS CODE</Text><Text style={s.groupCode}>{group.code}</Text><View style={s.shareRow}><Pressable accessibilityRole="button" onPress={async () => { await Clipboard.setStringAsync(group.code); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); }} style={s.smallAction}><Ionicons name="copy-outline" size={18} color={C.ink} /><Text style={s.smallActionText}>Copy Code</Text></Pressable><Pressable accessibilityRole="button" onPress={share} style={s.smallAction}><Ionicons name="share-outline" size={18} color={C.ink} /><Text style={s.smallActionText}>Share Invite</Text></Pressable></View></View>
    <View style={s.planCard}><View style={s.activeIcon}><Ionicons name={copy.icon} size={22} color={C.white} /></View><View style={{ flex: 1 }}><Text style={s.kicker}>{copy.label.toUpperCase()} · MEETING DETAILS</Text><Text style={s.cardTitle}>{group.start.name} → {group.destination.name}</Text><Text style={s.meta}>{group.start.address || group.start.area} · {group.destination.address || group.destination.area}</Text></View>{host ? <Pressable accessibilityRole="button" onPress={onChangeDestination}><Text style={s.link}>Change</Text></Pressable> : null}</View>
    <View style={s.sectionHead}><Text style={s.sectionTitle}>{copy.participants.toUpperCase()}</Text><View style={s.count}><Text style={s.countText}>{group.members.length}</Text></View></View>
    <View style={s.list}>{group.members.map((member, index) => { const isHost = member.id === group.hostId; return <View key={member.id} style={[s.memberRow, index < group.members.length - 1 && s.divider]}><Initials member={member} /><View style={{ flex: 1, marginLeft: 12 }}><Text style={s.memberName}>{member.name}{member.id === participantId ? ' (you)' : ''}</Text><Text style={s.meta}>{isHost ? 'Host' : `In the ${copy.noun} group`}</Text></View>{host && !isHost ? <Pressable accessibilityRole="button" accessibilityLabel={`Remove ${member.name}`} onPress={() => setRemoveId(member.id)} style={s.remove}><Ionicons name="close" size={18} color={C.red} /></Pressable> : null}</View>; })}</View>
    {group.members.length === 1 ? <Text style={s.emptyHint}>You’re the first one here. Share the code so your friends can join.</Text> : null}{error ? <View style={s.error}><Text style={s.errorText}>{error}</Text></View> : null}
  </ScrollView><View style={s.sticky}>{host ? <Button disabled={busy} label={busy ? `Starting ${copy.noun}…` : `Start ${copy.noun}`} icon="arrow-forward" onPress={onStart} /> : <View style={s.waiting}><ActivityIndicator color={C.ink} /><Text style={s.waitingText}>Waiting for the host to start…</Text></View>}<Pressable accessibilityRole="button" onPress={() => setConfirmLeave(true)}><Text style={s.leaveLink}>{host ? 'Cancel group' : 'Leave group'}</Text></Pressable></View><ConfirmDialog visible={confirmLeave} title={host ? 'Cancel this group?' : 'Leave this group?'} body={host ? 'The next participant will become host. If nobody else is here, the group will close.' : 'You will leave this private activity group.'} confirmLabel={host ? 'Cancel / Leave' : 'Leave group'} destructive onCancel={() => setConfirmLeave(false)} onConfirm={() => { setConfirmLeave(false); onLeave(); }} /><ConfirmDialog visible={Boolean(removeId)} title={`Remove ${removeName}?`} body="They will be removed from this activity and cannot use the same account to rejoin." confirmLabel="Remove participant" destructive onCancel={() => setRemoveId('')} onConfirm={() => { const target = removeId; setRemoveId(''); onRemove(target); }} /></SafeAreaView>;
}

function Stat({ label, value }: { label: string; value: string }) { return <View style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text></View>; }

function Summary({ summary, units, participantId, onConnect, onDone }: { summary: ActivitySummary; units: Profile['units']; participantId?: string; onConnect?: (targetId: string) => Promise<boolean>; onDone: () => void }) {
  const kind = summary.activity || 'ride'; const copy = activityCopy(kind); const [asked, setAsked] = useState<string[]>([]); const [matches, setMatches] = useState(summary.connections || []);
  const others = participantId ? summary.riders.filter((rider) => rider.id !== participantId) : summary.riders;
  const connectionKey = (targetId: string) => [participantId, targetId].sort().join(':');
  return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={[s.content, { flexGrow: 1 }]}><View style={s.summaryHero}><View style={s.finishIcon}><Ionicons name={copy.icon} size={34} color={C.ink} /></View><Text style={s.kicker}>{copy.noun.toUpperCase()} COMPLETE</Text><Text style={s.bigTitle}>{summary.riders.length > 1 ? 'Finished together.' : 'Nice work.'}</Text><Text style={s.body}>{summary.start?.name ? `${summary.start.name} → ` : ''}{summary.destination.name} · {new Date(summary.endedAt).toLocaleDateString()}</Text></View><View style={s.summaryStats}><Stat label="DURATION" value={formatDuration(summary.durationSeconds)} /><Stat label="DISTANCE" value={distanceText(summary.distanceKm, units)} /><Stat label={kind === 'run' ? 'AVG PACE' : 'AVG SPEED'} value={primaryMetricText(kind, summary.averageSpeedKmh, units)} /><Stat label="PEOPLE" value={String(summary.riders.length)} /></View><Text style={s.sectionTitle}>YOUR GROUP / KAKI</Text><View style={s.connectionList}>{others.map((rider) => { const matched = Boolean(participantId && matches.includes(connectionKey(rider.id))); const requested = asked.includes(rider.id); return <View key={rider.id} style={s.connectionRow}><Initials member={rider as ApiMember} size={46} /><View style={{ flex: 1 }}><Text style={s.memberName}>{rider.name}{rider.id === participantId ? ' (you)' : ''}</Text><Text style={s.meta}>{matched ? 'You both want to move together again' : requested ? 'Private unless they feel the same' : `Shared this ${copy.noun} with you`}</Text></View>{participantId && rider.id !== participantId ? <Pressable accessibilityRole="button" disabled={requested || matched} onPress={async () => { if (!onConnect) return; setAsked((current) => [...current, rider.id]); if (await onConnect(rider.id)) setMatches((current) => [...current, connectionKey(rider.id)]); }} style={[s.connectButton, (requested || matched) && s.connectButtonDone]}><Ionicons name={matched ? 'people' : requested ? 'checkmark' : 'hand-left-outline'} size={17} color={C.ink} /><Text style={s.connectText}>{matched ? 'Kaki' : requested ? 'Sent' : 'Again'}</Text></Pressable> : null}</View>; })}</View>{others.length > 0 && participantId ? <View style={s.privateNote}><Ionicons name="lock-closed-outline" size={17} color={C.ink} /><Text style={s.meta}>“Again” is double-blind. Nobody sees it unless they choose you too.</Text></View> : null}</ScrollView><View style={s.sticky}><Button label="Done" icon="arrow-forward" onPress={onDone} /></View></SafeAreaView>;
}
function SummaryRow({ ride, units, onPress }: { ride: ActivitySummary; units: Profile['units']; onPress: () => void }) { const kind = ride.activity || 'ride'; return <Pressable accessibilityRole="button" accessibilityLabel={`Open ${activityCopy(kind).label} from ${new Date(ride.endedAt).toLocaleDateString()}`} onPress={onPress} style={s.summaryRow}><View style={s.activeIcon}><Ionicons name={activityCopy(kind).icon} size={21} color={C.white} /></View><View style={{ flex: 1 }}><Text style={s.memberName}>{ride.start?.name ? `${ride.start.name} → ` : ''}{ride.destination.name}</Text><Text style={s.meta}>{activityCopy(kind).label} · {new Date(ride.endedAt).toLocaleDateString()} · {distanceText(ride.distanceKm, units, 1)} · {formatDuration(ride.durationSeconds)}</Text></View><Ionicons name="chevron-forward" size={19} color={C.soft} /></Pressable>; }
function History({ history, units, onBack, onOpen }: { history: ActivitySummary[]; units: Profile['units']; onBack: () => void; onOpen: (ride: ActivitySummary) => void }) { return <SafeAreaView style={s.screen}><Header title="ACTIVITY HISTORY" onBack={onBack} /><ScrollView contentContainerStyle={s.content}>{history.map((ride) => <SummaryRow key={ride.code} units={units} ride={ride} onPress={() => onOpen(ride)} />)}</ScrollView></SafeAreaView>; }
function Settings({ profile, permission, email, onBack, onSave, onSignOut }: { profile: Profile; permission: string; email: string; onBack: () => void; onSave: (profile: Profile) => void; onSignOut: () => void }) { const [draft, setDraft] = useState(profile); const [confirmSignOut, setConfirmSignOut] = useState(false); return <SafeAreaView style={s.screen}><Header title="SETTINGS" onBack={onBack} /><ScrollView contentContainerStyle={s.content}><Setting label="Account" detail={email}><Ionicons name="shield-checkmark-outline" size={22} color={C.ink} /></Setting><Field label="DISPLAY NAME"><TextInput value={draft.displayName} onChangeText={(displayName) => setDraft({ ...draft, displayName })} style={s.input} placeholder="Your name" /></Field><Setting label="Voice cheers" detail="Opt in to spoken incoming cheers"><Switch value={draft.voiceEnabled} onValueChange={(voiceEnabled) => setDraft({ ...draft, voiceEnabled })} trackColor={{ true: C.ink }} /></Setting><Setting label="Units" detail={draft.units === 'metric' ? 'Kilometres and km/h' : 'Miles and mph'}><Pressable accessibilityRole="button" onPress={() => setDraft({ ...draft, units: draft.units === 'metric' ? 'imperial' : 'metric' })}><Text style={s.link}>{draft.units === 'metric' ? 'Metric' : 'Imperial'}</Text></Pressable></Setting><Setting label="Location permission" detail={permission}><Pressable accessibilityRole="button" onPress={() => Linking.openSettings()}><Text style={s.link}>Settings</Text></Pressable></Setting>{__DEV__ ? <Setting label="Demo mode" detail="Development only · simulated location"><Switch value={draft.demoMode} onValueChange={(demoMode) => setDraft({ ...draft, demoMode })} /></Setting> : null}<View style={s.about}><Logo /><Text style={s.meta}>Paladin v1.0 · Built for moving together.</Text><Pressable accessibilityRole="button" onPress={() => setConfirmSignOut(true)}><Text style={[s.leaveLink, { fontSize: 14 }]}>Sign out</Text></Pressable></View></ScrollView><View style={s.sticky}><Button label="Save Settings" onPress={() => onSave({ ...draft, displayName: draft.displayName.trim() })} /></View><ConfirmDialog visible={confirmSignOut} title="Sign out?" body="Your active activity stays linked to this account and can resume after you sign back in." confirmLabel="Sign out" destructive onCancel={() => setConfirmSignOut(false)} onConfirm={() => { setConfirmSignOut(false); onSignOut(); }} /></SafeAreaView>; }
function Setting({ label, detail, children }: { label: string; detail: string; children: React.ReactNode }) { return <View style={s.setting}><View style={{ flex: 1 }}><Text style={s.memberName}>{label}</Text><Text style={s.meta}>{detail}</Text></View>{children}</View>; }

export default function App() {
  const [screen, setScreen] = useState<Screen>('boot'); const [mode, setMode] = useState<Mode>('create'); const [profile, setProfile] = useState(EMPTY_PROFILE); const [authUser, setAuthUser] = useState<AuthUser | null>(null); const [group, setGroup] = useState<ApiGroup | null>(null); const [participantId, setParticipantId] = useState(''); const [history, setHistory] = useState<ActivitySummary[]>([]); const [summary, setSummary] = useState<ActivitySummary | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [online, setOnline] = useState(true); const [reconnecting, setReconnecting] = useState(false); const [permission, setPermission] = useState('Not requested'); const distanceRef = useRef(0); const restoreStarted = useRef(false); const refreshInFlight = useRef(false);
  const finishLocally = async (rideSummary: ActivitySummary) => { await storage.addHistory(rideSummary); await storage.clearSession(); await storage.clearRideStats(); await stopBackgroundTracking().catch(() => undefined); const cloudHistory = await activityService.history().then((result) => result.rides).catch(() => storage.history()); setHistory(cloudHistory); setSummary(rideSummary); setScreen('summary'); };
  const restore = async () => {
    const [hasOnboarded, savedProfile, savedSession, savedHistory] = await Promise.all([storage.hasOnboarded(), storage.profile(), storage.session(), storage.history()]);
    setProfile(savedProfile); setHistory(savedHistory);
    if (!localDemoMode && (!authService.configured || (!__DEV__ && !process.env.EXPO_PUBLIC_API_URL))) return setScreen('configuration');
    const session = localDemoMode ? { user: localDemoUser } : await authService.currentSession(); setAuthUser(session?.user || null);
    const status = await locationPermissionStatus().catch(() => null);
    if (status) setPermission(status.foreground.status === 'granted' ? (status.background?.status === 'granted' ? 'Always allowed' : 'While using app') : 'Not allowed');
    if (!hasOnboarded) return setScreen('onboarding');
    if (!session?.user) return setScreen('auth');
    const [cloudProfile, cloudHistory] = await Promise.all([activityService.profile().then((result) => result.profile).catch(() => null), activityService.history().then((result) => result.rides).catch(() => savedHistory)]);
    const mergedProfile = cloudProfile ? { ...savedProfile, ...cloudProfile } : { ...savedProfile, displayName: savedProfile.displayName || String(session.user.user_metadata?.display_name || '') };
    setProfile(mergedProfile); await storage.saveProfile(mergedProfile); setHistory(cloudHistory); setReconnecting(true);
    try {
      const active = savedSession
        ? await activityService.resume(savedSession.code, savedProfile.deviceId).then((result) => ({ group: result.group, participantId: result.participantId }))
        : await activityService.active();
      if (!active.group || !active.participantId) return setScreen('home');
      setGroup(active.group); setParticipantId(active.participantId);
      await storage.saveSession({ code: active.group.code, participantId: active.participantId, group: active.group });
      if (active.group.status === 'ended' && active.group.summary) await finishLocally(active.group.summary);
      else setScreen(active.group.status === 'active' ? 'active' : 'lobby');
    } catch {
      if (savedSession?.group && savedSession.group.status !== 'ended') { setGroup(savedSession.group); setParticipantId(savedSession.participantId); setScreen(savedSession.group.status === 'active' ? 'active' : 'lobby'); }
      else setScreen('home');
    } finally { setReconnecting(false); }
  };
  useEffect(() => { if (!restoreStarted.current) { restoreStarted.current = true; restore(); } const unsubscribe = NetInfo.addEventListener((state) => setOnline(Boolean(state.isConnected && state.isInternetReachable !== false))); return unsubscribe; }, []);
  useEffect(() => authService.onAuthStateChange((event, session) => { setAuthUser(session?.user || null); if (event === 'PASSWORD_RECOVERY') setScreen('passwordReset'); if (event === 'SIGNED_OUT') { setGroup(null); setParticipantId(''); setScreen('auth'); } }), []);
  useEffect(() => { const open = async ({ url }: { url: string }) => { try { if (await authService.handleAuthUrl(url)) setScreen('passwordReset'); } catch { setError('That password reset link is invalid or expired. Request a new one.'); setScreen('auth'); } }; Linking.getInitialURL().then((url) => { if (url) open({ url }); }); const listener = Linking.addEventListener('url', open); return () => listener.remove(); }, []);
  const refresh = async () => { if (!group || refreshInFlight.current) return; refreshInFlight.current = true; try { if (participantId) await activityService.heartbeat(group.code, participantId); const result = await activityService.snapshot(group.code); setGroup(result.group); const self = result.group.members.find((member) => member.id === participantId); await storage.saveSession({ code: result.group.code, participantId, group: result.group, sharingEnabled: self?.visibility !== 'paused' }); setReconnecting(false); if (result.group.status === 'ended' && result.group.summary) await finishLocally(result.group.summary); else if (result.group.status === 'active' && screen === 'lobby') setScreen('active'); } catch { setReconnecting(true); } finally { refreshInFlight.current = false; } };
  useEffect(() => { const app = AppState.addEventListener('change', (state) => { if (state === 'active' && group) refresh(); }); return () => app.remove(); }, [group?.code, participantId, screen]);
  useEffect(() => { if (!group || !['lobby', 'active'].includes(screen)) return; const timer = setInterval(refresh, screen === 'active' ? 2500 : 1800); refresh(); return () => clearInterval(timer); }, [group?.code, screen]);
  const submit = async (data: ActivitySetupValue) => { if (busy) return; setBusy(true); setError(''); try { const result = mode === 'create' ? await activityService.create({ name: data.name, deviceId: profile.deviceId, activity: data.activity, rideName: data.activityName, groupName: data.groupName, start: toApiPoint(data.route.start), destination: toApiPoint(data.route.end) }) : await activityService.join(data.code, data.name, profile.deviceId); const updated = { ...profile, displayName: data.name }; await Promise.all([storage.saveProfile(updated), activityService.saveProfile({ displayName: updated.displayName, voiceEnabled: updated.voiceEnabled, units: updated.units })]); await storage.saveSession({ code: result.group.code, participantId: result.participantId, group: result.group }); setProfile(updated); setGroup(result.group); setParticipantId(result.participantId); setScreen(result.group.status === 'active' ? 'active' : 'lobby'); } catch (e) { setError(e instanceof ApiError ? e.message : 'Paladin could not complete that action.'); } finally { setBusy(false); } };
  const start = async () => { if (!group || busy) return; setBusy(true); setError(''); try { const result = await activityService.start(group.code, participantId); setGroup(result.group); await Promise.all([storage.saveRideStats({ code: group.code, distanceKm: 0, maxSpeedKmh: 0 }), storage.setSharingEnabled(false)]); setScreen('active'); } catch (e) { setError(e instanceof Error ? e.message : 'The activity could not start.'); } finally { setBusy(false); } };
  const leave = async () => { if (!group || busy) return; setBusy(true); setError(''); try { await activityService.leave(group.code, participantId); await storage.clearSession(); setGroup(null); setScreen('home'); } catch (e) { setError(e instanceof Error ? e.message : 'Could not leave the group. Try again.'); } finally { setBusy(false); } };
  const leaveActive = async () => { if (!group || busy) return; setBusy(true); setError(''); await storage.setSharingEnabled(false); await stopBackgroundTracking().catch(() => undefined); try { await activityService.presence(group.code, participantId, { visibility: 'paused' }); await activityService.leave(group.code, participantId); } catch { /* Server expiry hides the last coordinate if the device is offline. */ } finally { await storage.clearSession(); await storage.clearRideStats(); setGroup(null); setScreen('home'); setBusy(false); } };
  const end = async (distance: number) => { if (!group || busy) return; setBusy(true); setError(''); try { const result = await activityService.end(group.code, participantId, distance); setGroup(result.group); if (result.group.summary) await finishLocally(result.group.summary); } catch (e) { setError(e instanceof Error ? e.message : 'Could not finish the activity. Try again.'); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!group || busy) return; setBusy(true); setError(''); try { const result = await activityService.leave(group.code, participantId, id); setGroup(result.group); } catch (e) { setError(e instanceof Error ? e.message : 'Could not remove that participant.'); } finally { setBusy(false); } };
  const changeDestination = async () => { if (!group || busy) return; const options = ROUTE_POINTS.filter((point) => point.name !== group.start.name); const currentIndex = options.findIndex((point) => point.name === group.destination.name); const next = options[(currentIndex + 1 + options.length) % options.length]; setBusy(true); setError(''); try { const result = await activityService.destination(group.code, participantId, toApiPoint(next)); setGroup(result.group); } catch (e) { setError(e instanceof Error ? e.message : 'Could not change the meeting details.'); } finally { setBusy(false); } };
  if (screen === 'boot') return <View style={[s.fill, s.center]}><Logo /><ActivityIndicator color={C.ink} style={{ marginTop: 24 }} /><Text style={[s.meta, { marginTop: 10 }]}>Restoring Paladin…</Text></View>;
  if (screen === 'configuration') return <ConfigurationScreen />;
  if (screen === 'onboarding') return <Onboarding onDone={async () => { await storage.completeOnboarding(); setScreen(localDemoMode || authUser ? 'home' : 'auth'); }} />;
  if (screen === 'auth') return <AuthScreen onAuthenticated={async (user) => { setAuthUser(user); setScreen('boot'); await restore(); }} />;
  if (screen === 'passwordReset') return <PasswordReset onDone={() => setScreen('home')} />;
  if (screen === 'home') return <><StatusBar style="dark" /><Home profile={profile} active={group?.status === 'active' ? group : null} history={history} onCreate={() => { setMode('create'); setError(''); setScreen('setup'); }} onJoin={() => { setMode('join'); setError(''); setScreen('setup'); }} onResume={() => setScreen('active')} onSettings={() => setScreen('settings')} onHistory={() => setScreen('history')} onOpenRide={(ride) => { setSummary(ride); setScreen('summary'); }} /></>;
  if (screen === 'setup') return <ActivitySetupScreen mode={mode} profile={profile} busy={busy} error={error} onBack={() => setScreen('home')} onSubmit={submit} />;
  if (screen === 'lobby' && group) return <Lobby group={group} participantId={participantId} busy={busy} error={error} onStart={start} onLeave={leave} onChangeDestination={changeDestination} onRemove={remove} />;
  if (screen === 'active' && group) return <LiveActivityScreen group={group} participantId={participantId} profile={profile} online={online} reconnecting={reconnecting} onLeave={leaveActive} onEnd={end} onStats={(distance) => { distanceRef.current = distance; }} />;
  if (screen === 'summary' && summary) return <Summary summary={summary} units={profile.units} participantId={group?.status === 'ended' ? participantId : undefined} onConnect={group?.status === 'ended' ? async (targetId) => { const result = await activityService.connect(group.code, participantId, targetId); setGroup(result.group); if (result.group.summary) { setSummary(result.group.summary); await storage.addHistory(result.group.summary); } return result.matched; } : undefined} onDone={() => { setSummary(null); setGroup(null); setParticipantId(''); setScreen('home'); }} />;
  if (screen === 'history') return <History history={history} units={profile.units} onBack={() => setScreen('home')} onOpen={(ride) => { setSummary(ride); setScreen('summary'); }} />;
  if (screen === 'settings') return <Settings profile={profile} permission={permission} email={authUser?.email || ''} onBack={() => setScreen('home')} onSave={async (value) => { await Promise.all([storage.saveProfile(value), activityService.saveProfile({ displayName: value.displayName, voiceEnabled: value.voiceEnabled, units: value.units })]); setProfile(value); setScreen('home'); }} onSignOut={async () => { await stopBackgroundTracking().catch(() => undefined); await storage.clearAccountData(); setHistory([]); setProfile(EMPTY_PROFILE); await authService.signOut(); }} />;
  return null;
}

const s = StyleSheet.create({
  fill: { flex: 1 }, center: { alignItems: 'center', justifyContent: 'center', backgroundColor: C.cream }, screen: { flex: 1, backgroundColor: C.cream },
  header: { minHeight: 66, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerTitle: { fontSize: 11, fontWeight: '900', color: C.ink, letterSpacing: 1.5 }, iconButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  logo: { flexDirection: 'row', alignItems: 'center', gap: 9 }, logoMark: { width: 34, height: 34, borderRadius: 17, backgroundColor: C.ink, overflow: 'hidden' }, logoDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.lime, position: 'absolute', top: 8, right: 8 }, logoTrail: { width: 24, height: 4, borderRadius: 2, backgroundColor: C.orange, position: 'absolute', bottom: 8, left: 4, transform: [{ rotate: '-35deg' }] }, logoText: { color: C.ink, fontWeight: '900', letterSpacing: 1.3, fontSize: 15 },
  onboarding: { flex: 1, padding: 24, paddingTop: 34, justifyContent: 'space-between' }, onboardHero: { alignItems: 'flex-start' }, onboardIcon: { width: 92, height: 92, borderRadius: 31, backgroundColor: C.lime, alignItems: 'center', justifyContent: 'center', marginBottom: 32 }, onboardPrivacy: { marginTop: 24, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 18, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 11 }, onboardPrivacyText: { flex: 1, color: C.ink, fontSize: 12, lineHeight: 18, fontWeight: '700' }, kicker: { color: C.orange, fontSize: 10, fontWeight: '900', letterSpacing: 1.6, marginBottom: 9 }, bigTitle: { color: C.ink, fontSize: 42, lineHeight: 44, fontWeight: '900', letterSpacing: -1.5 }, body: { color: C.soft, fontSize: 15, lineHeight: 22, marginTop: 13 }, dots: { flexDirection: 'row', justifyContent: 'center', gap: 7, marginBottom: 20 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.line }, dotActive: { width: 24, backgroundColor: C.orange }, skip: { color: C.soft, fontWeight: '700', textAlign: 'center', padding: 14 },
  authWrap: { flex: 1, paddingHorizontal: 24, paddingTop: 28 }, authContent: { paddingTop: 52, paddingBottom: 50 },
  home: { paddingHorizontal: 24, paddingBottom: 30, gap: 28 }, homeHeader: { paddingTop: Platform.OS === 'android' ? 22 : 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, heroTitle: { color: C.ink, fontSize: 44, lineHeight: 46, fontWeight: '900', letterSpacing: -1.8 }, activeCard: { borderRadius: 22, backgroundColor: C.lime, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 13 }, activeIcon: { width: 47, height: 47, borderRadius: 15, backgroundColor: C.orange, alignItems: 'center', justifyContent: 'center' }, cardTitle: { color: C.ink, fontSize: 17, fontWeight: '800' }, meta: { color: C.soft, fontSize: 11, lineHeight: 16, marginTop: 3 },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }, sectionTitle: { color: C.ink, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, link: { color: C.orange, fontSize: 12, fontWeight: '800' }, empty: { backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 20, alignItems: 'center', padding: 24 }, emptyTitle: { color: C.ink, fontSize: 15, fontWeight: '800', marginTop: 8 }, kakiRow: { minHeight: 66, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 18, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 8 },
  content: { padding: 24, paddingBottom: 125 }, pageTitle: { color: C.ink, fontSize: 36, lineHeight: 39, fontWeight: '900', letterSpacing: -1.2 }, fieldLabel: { color: C.ink, fontSize: 10, fontWeight: '900', letterSpacing: 1.4, marginBottom: 9 }, input: { height: 58, borderRadius: 17, borderWidth: 1, borderColor: C.line, backgroundColor: C.paper, paddingHorizontal: 16, color: C.ink, fontSize: 16, fontWeight: '600' }, error: { marginTop: 20, padding: 13, borderRadius: 14, backgroundColor: '#FCE5DE', flexDirection: 'row', alignItems: 'center', gap: 9 }, errorText: { flex: 1, color: C.red, fontSize: 12, lineHeight: 17 }, sticky: { paddingHorizontal: 24, paddingTop: 12, paddingBottom: Platform.OS === 'android' ? 22 : 12, backgroundColor: C.cream, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: C.line },
  codeCard: { backgroundColor: C.ink, borderRadius: 25, padding: 22 }, codeEyebrow: { color: C.mint, fontSize: 9, fontWeight: '900', letterSpacing: 1.5 }, groupCode: { color: C.white, fontSize: 42, letterSpacing: 8, fontWeight: '900', textAlign: 'center', marginVertical: 16 }, shareRow: { flexDirection: 'row', gap: 10 }, smallAction: { flex: 1, height: 44, borderRadius: 14, backgroundColor: C.lime, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, smallActionText: { color: C.ink, fontSize: 12, fontWeight: '800' }, planCard: { marginTop: 15, padding: 15, borderRadius: 20, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center', gap: 12 }, count: { width: 24, height: 24, borderRadius: 12, backgroundColor: C.mint, alignItems: 'center', justifyContent: 'center' }, countText: { color: C.ink, fontSize: 11, fontWeight: '900' }, list: { borderRadius: 20, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, paddingHorizontal: 15 }, memberRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13 }, divider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line }, memberName: { color: C.ink, fontSize: 14, fontWeight: '800' }, avatar: { alignItems: 'center', justifyContent: 'center' }, avatarText: { color: C.white, fontWeight: '900', fontSize: 13 }, ready: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#59B87C', alignItems: 'center', justifyContent: 'center' }, remove: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#FCE5DE', alignItems: 'center', justifyContent: 'center' }, emptyHint: { color: C.soft, fontSize: 12, textAlign: 'center', marginTop: 14 }, waiting: { height: 58, borderRadius: 29, backgroundColor: C.mint, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }, waitingText: { color: C.ink, fontWeight: '800' }, leaveLink: { color: C.red, fontWeight: '700', fontSize: 12, textAlign: 'center', paddingTop: 13 },
  stat: { width: '50%', paddingVertical: 8, paddingHorizontal: 9 }, statLabel: { color: C.soft, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, statValue: { color: C.ink, fontSize: 17, fontWeight: '900', marginTop: 3 },
  summaryHero: { alignItems: 'center', marginTop: 24, marginBottom: 30 }, finishIcon: { width: 82, height: 82, borderRadius: 28, backgroundColor: C.lime, alignItems: 'center', justifyContent: 'center', marginBottom: 20 }, summaryStats: { backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 22, flexDirection: 'row', flexWrap: 'wrap', marginBottom: 28 }, avatarStack: { flexDirection: 'row', gap: 8, marginTop: 12 }, connectionList: { marginTop: 12, borderRadius: 20, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, paddingHorizontal: 14 }, connectionRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line }, connectButton: { minWidth: 74, minHeight: 38, paddingHorizontal: 10, borderRadius: 19, backgroundColor: C.lime, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, connectButtonDone: { backgroundColor: C.mint }, connectText: { color: C.ink, fontSize: 11, fontWeight: '900' }, privateNote: { marginTop: 12, borderRadius: 15, backgroundColor: C.mint, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }, summaryRow: { padding: 13, borderRadius: 18, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 9 }, setting: { minHeight: 72, backgroundColor: C.paper, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 }, about: { alignItems: 'center', marginTop: 42, gap: 9 },
});
