import { StatusBar } from 'expo-status-bar';
import { LinearGradient } from 'expo-linear-gradient';
import * as Haptics from 'expo-haptics';
import * as Location from 'expo-location';
import * as Speech from 'expo-speech';
import * as Clipboard from 'expo-clipboard';
import NetInfo from '@react-native-community/netinfo';
import { Ionicons } from '@expo/vector-icons';
import { useEffect, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator, Alert, Animated, AppState, KeyboardAvoidingView, Linking, Modal, Platform,
  Pressable, SafeAreaView, ScrollView, Share, StyleSheet, Switch, Text, TextInput, View,
} from 'react-native';
import { ApiError, groupApi, type ApiGroup, type ApiMember, type RideSummary } from './src/api';
import { GroupMap } from './src/GroupMap';
import { locationPermissionStatus, requestRideLocation, startBackgroundTracking, stopBackgroundTracking } from './src/locationTracking';
import { acceptedMovement, elapsedSeconds, formatDuration, freshness } from './src/rideUtils';
import { storage, type Profile } from './src/storage';

type Screen = 'boot' | 'onboarding' | 'home' | 'setup' | 'lobby' | 'active' | 'summary' | 'settings' | 'history';
type Mode = 'create' | 'join';
type Destination = ApiGroup['destination'] & { icon: keyof typeof Ionicons.glyphMap };

const C = { cream: '#F7F3EA', paper: '#FFFCF6', ink: '#18352C', soft: '#527068', orange: '#FF6846', mint: '#BCE9D9', lime: '#D7F26D', blue: '#7CA8F8', line: '#DADDD4', white: '#FFFFFF', red: '#A33D2C' };
const DESTINATIONS: Destination[] = [
  { name: 'Marina Barrage', area: 'Marina Bay', address: '8 Marina Gardens Drive', distance: '5.2 km', latitude: 1.2807, longitude: 103.8712, icon: 'water-outline' },
  { name: 'East Coast Park', area: 'Marine Cove', address: '1000 East Coast Parkway', distance: '8.4 km', latitude: 1.3018, longitude: 103.9127, icon: 'leaf-outline' },
  { name: 'MacRitchie Reservoir', area: 'Central Water Catchment', address: 'Lornie Road', distance: '10.1 km', latitude: 1.3448, longitude: 103.8224, icon: 'trail-sign-outline' },
  { name: 'Rail Corridor', area: 'Bukit Timah', address: 'King Albert Park', distance: '7.8 km', latitude: 1.3324, longitude: 103.7817, icon: 'git-branch-outline' },
];
const CHEERS = ['Let’s go!', 'Wait up!', 'Nice!', 'I’m behind', 'All good', 'Stop ahead'];
const EMPTY_PROFILE: Profile = { deviceId: '', displayName: '', voiceEnabled: true, units: 'metric', demoMode: false };

function Button({ label, onPress, secondary, danger, disabled, icon }: { label: string; onPress: () => void; secondary?: boolean; danger?: boolean; disabled?: boolean; icon?: keyof typeof Ionicons.glyphMap }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, secondary && s.buttonSecondary, danger && s.buttonDanger, disabled && s.disabled, pressed && s.pressed]}>
    <Text style={[s.buttonText, secondary && s.buttonTextSecondary]}>{label}</Text>{icon ? <Ionicons name={icon} size={19} color={secondary ? C.ink : C.white} /> : null}
  </Pressable>;
}

function Header({ title, onBack, right }: { title: string; onBack?: () => void; right?: React.ReactNode }) {
  return <View style={s.header}>{onBack ? <Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={onBack} style={s.iconButton}><Ionicons name="arrow-back" size={21} color={C.ink} /></Pressable> : <Logo />}
    <Text style={s.headerTitle}>{title}</Text>{right || <View style={{ width: 42 }} />}</View>;
}

function Logo() { return <View style={s.logo}><View style={s.logoMark}><View style={s.logoDot} /><View style={s.logoTrail} /></View><Text style={s.logoText}>PALADIN</Text></View>; }
function Initials({ member, size = 44 }: { member: Pick<ApiMember, 'initials' | 'color'>; size?: number }) { return <View style={[s.avatar, { width: size, height: size, borderRadius: size / 2, backgroundColor: member.color }]}><Text style={s.avatarText}>{member.initials}</Text></View>; }
function NetworkPill({ online, connecting }: { online: boolean; connecting: boolean }) { return !online || connecting ? <View style={s.networkPill}><ActivityIndicator size="small" color={C.ink} /><Text style={s.networkText}>{online ? 'Reconnecting…' : 'Offline · ride stays active'}</Text></View> : null; }
function distanceText(km: number, units: Profile['units'], decimals = 2) { return units === 'imperial' ? `${(km * 0.621371).toFixed(decimals)} mi` : `${km.toFixed(decimals)} km`; }
function speedText(kmh: number, units: Profile['units']) { return units === 'imperial' ? `${(kmh * 0.621371).toFixed(1)} mph` : `${kmh.toFixed(1)} km/h`; }

function Onboarding({ onDone }: { onDone: () => Promise<void> }) {
  const [step, setStep] = useState(0); const [busy, setBusy] = useState(false);
  const pages = [
    { icon: 'people-circle-outline' as const, kicker: 'WELCOME TO PALADIN', title: 'Ride together.\nStay together.', body: 'See where your friends are, share ride information, and stay connected with quick voice cheers.' },
    { icon: 'location-outline' as const, kicker: 'LIVE LOCATION', title: 'Your group,\non one map.', body: 'Paladin uses your location during active rides so your friends can see where you are. Sharing stops when you leave or finish.' },
    { icon: 'headset-outline' as const, kicker: 'SAFE & SIMPLE', title: 'Ready to\nhit the road.', body: 'Large controls and one-tap cheers keep interaction quick. Only use Paladin while safely stopped.' },
  ]; const page = pages[step];
  const next = async () => { if (step === 1) await requestRideLocation(); if (step < pages.length - 1) setStep(step + 1); else { setBusy(true); await onDone(); } };
  return <LinearGradient colors={[C.cream, '#E5F1E6']} style={s.fill}><SafeAreaView style={s.onboarding}><Logo /><View style={s.onboardHero}><View style={s.onboardIcon}><Ionicons name={page.icon} size={54} color={C.ink} /></View><Text style={s.kicker}>{page.kicker}</Text><Text style={s.bigTitle}>{page.title}</Text><Text style={s.body}>{page.body}</Text></View><View><View style={s.dots}>{pages.map((_, index) => <View key={index} style={[s.dot, index === step && s.dotActive]} />)}</View><Button disabled={busy} label={step === pages.length - 1 ? 'Open Paladin' : step === 1 ? 'Allow location' : 'Continue'} icon="arrow-forward" onPress={next} />{step === 1 ? <Pressable onPress={() => setStep(2)}><Text style={s.skip}>Not now</Text></Pressable> : null}</View></SafeAreaView></LinearGradient>;
}

function Home({ profile, active, history, onCreate, onJoin, onResume, onSettings, onHistory, onOpenRide }: { profile: Profile; active: ApiGroup | null; history: RideSummary[]; onCreate: () => void; onJoin: () => void; onResume: () => void; onSettings: () => void; onHistory: () => void; onOpenRide: (ride: RideSummary) => void }) {
  return <LinearGradient colors={[C.cream, '#E8F2E6']} style={s.fill}><SafeAreaView style={s.fill}><ScrollView contentContainerStyle={s.home}>
    <View style={s.homeHeader}><Logo /><Pressable accessibilityLabel="Settings" onPress={onSettings} style={s.iconButton}><Ionicons name="settings-outline" size={21} color={C.ink} /></Pressable></View>
    <View><Text style={s.kicker}>{profile.displayName ? `WELCOME BACK, ${profile.displayName.toUpperCase()}` : 'YOUR PEOPLE. ONE ROUTE.'}</Text><Text style={s.heroTitle}>Never lose a <Text style={{ color: C.orange, fontStyle: 'italic' }}>kaki.</Text></Text><Text style={s.body}>Create a cycling group, share one code, and keep everyone connected from rollout to finish.</Text></View>
    {active ? <View style={s.activeCard}><View style={s.activeIcon}><Ionicons name="bicycle" size={25} color={C.white} /></View><View style={{ flex: 1 }}><Text style={s.kicker}>ACTIVE RIDE · {active.code}</Text><Text style={s.cardTitle}>{active.destination.name}</Text><Text style={s.meta}>{active.members.length} rider{active.members.length === 1 ? '' : 's'} connected</Text></View><Ionicons name="chevron-forward" size={20} color={C.ink} /></View> : null}
    <View style={{ gap: 11 }}>{active ? <Button label="Resume Ride" icon="navigate" onPress={onResume} /> : <Button label="Create Ride" icon="add" onPress={onCreate} />}<Button label="Join Ride" icon="keypad-outline" secondary onPress={onJoin} /></View>
    <View><View style={s.sectionHead}><Text style={s.sectionTitle}>RECENT RIDES</Text>{history.length ? <Pressable onPress={onHistory}><Text style={s.link}>View all</Text></Pressable> : null}</View>{history.length ? history.slice(0, 2).map((ride) => <SummaryRow key={ride.code} units={profile.units} ride={ride} onPress={() => onOpenRide(ride)} />) : <View style={s.empty}><Ionicons name="trail-sign-outline" size={30} color={C.soft} /><Text style={s.emptyTitle}>No rides yet</Text><Text style={s.meta}>Create a group and hit the road.</Text></View>}</View>
  </ScrollView></SafeAreaView></LinearGradient>;
}

function Setup({ mode, profile, busy, error, onBack, onSubmit }: { mode: Mode; profile: Profile; busy: boolean; error: string; onBack: () => void; onSubmit: (data: { name: string; code: string; rideName: string; groupName: string; destination: Destination }) => void }) {
  const [name, setName] = useState(profile.displayName); const [code, setCode] = useState(''); const [rideName, setRideName] = useState(''); const [groupName, setGroupName] = useState(''); const [destination, setDestination] = useState(DESTINATIONS[0]);
  const valid = name.trim().length >= 2 && (mode === 'create' || code.length === 6);
  return <SafeAreaView style={s.screen}><KeyboardAvoidingView style={s.fill} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Header title={mode === 'create' ? 'CREATE RIDE' : 'JOIN RIDE'} onBack={onBack} /><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Text style={s.kicker}>{mode === 'create' ? 'NEW GROUP' : 'ENTER YOUR CODE'}</Text><Text style={s.pageTitle}>{mode === 'create' ? 'Plan the ride.' : 'Your group is waiting.'}</Text><Text style={s.body}>{mode === 'create' ? 'Keep it lightweight. You can change the destination before starting.' : 'Codes are six letters or numbers and are not case-sensitive.'}</Text>
    <Field label="DISPLAY NAME"><TextInput value={name} onChangeText={setName} placeholder="What should we call you?" placeholderTextColor="#97A59F" style={s.input} maxLength={24} /></Field>
    {mode === 'join' ? <Field label="GROUP CODE"><TextInput value={code} onChangeText={(value) => setCode(value.trim().toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6))} placeholder="CCAM34" placeholderTextColor="#97A59F" style={[s.input, s.codeInput]} autoCapitalize="characters" /></Field> : <>
      <Field label="RIDE NAME · OPTIONAL"><TextInput value={rideName} onChangeText={setRideName} placeholder="Sunday morning spin" placeholderTextColor="#97A59F" style={s.input} maxLength={50} /></Field>
      <Field label="GROUP NAME · OPTIONAL"><TextInput value={groupName} onChangeText={setGroupName} placeholder="East Side Kaki" placeholderTextColor="#97A59F" style={s.input} maxLength={40} /></Field>
      <Field label="DESTINATION"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 10 }}>{DESTINATIONS.map((item) => <Pressable key={item.name} onPress={() => setDestination(item)} style={[s.destination, destination.name === item.name && s.destinationActive]}><Ionicons name={item.icon} size={22} color={destination.name === item.name ? C.white : C.ink} /><Text style={[s.destinationName, destination.name === item.name && { color: C.white }]}>{item.name}</Text><Text style={[s.meta, destination.name === item.name && { color: '#E8F3EF' }]}>{item.address}</Text></Pressable>)}</ScrollView></Field>
    </>}{error ? <View style={s.error}><Ionicons name="alert-circle" size={19} color={C.red} /><Text style={s.errorText}>{error}</Text></View> : null}
  </ScrollView><View style={s.sticky}><Button disabled={!valid || busy} label={busy ? (mode === 'create' ? 'Creating ride…' : 'Joining ride…') : mode === 'create' ? 'Create Ride' : 'Join Ride'} icon="arrow-forward" onPress={() => onSubmit({ name: name.trim(), code, rideName: rideName.trim(), groupName: groupName.trim(), destination })} /></View></KeyboardAvoidingView></SafeAreaView>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <View style={{ marginTop: 26 }}><Text style={s.fieldLabel}>{label}</Text>{children}</View>; }

function Lobby({ group, participantId, busy, error, onStart, onLeave, onChangeDestination, onRemove }: { group: ApiGroup; participantId: string; busy: boolean; error: string; onStart: () => void; onLeave: () => void; onChangeDestination: () => void; onRemove: (id: string) => void }) {
  const host = group.hostId === participantId;
  const share = () => Share.share({ message: `Join my Paladin ride to ${group.destination.name}. Group code: ${group.code}` });
  return <SafeAreaView style={s.screen}><Header title="GROUP LOBBY" onBack={onLeave} /><ScrollView contentContainerStyle={s.content}>
    <View style={s.codeCard}><Text style={s.codeEyebrow}>SHARE THIS CODE</Text><Text style={s.groupCode}>{group.code}</Text><View style={s.shareRow}><Pressable onPress={async () => { await Clipboard.setStringAsync(group.code); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); }} style={s.smallAction}><Ionicons name="copy-outline" size={18} color={C.ink} /><Text style={s.smallActionText}>Copy Code</Text></Pressable><Pressable onPress={share} style={s.smallAction}><Ionicons name="share-outline" size={18} color={C.ink} /><Text style={s.smallActionText}>Share Invite</Text></Pressable></View></View>
    <View style={s.planCard}><View style={s.activeIcon}><Ionicons name="flag" size={22} color={C.white} /></View><View style={{ flex: 1 }}><Text style={s.kicker}>DESTINATION</Text><Text style={s.cardTitle}>{group.destination.name}</Text><Text style={s.meta}>{group.destination.address || group.destination.area}</Text></View>{host ? <Pressable onPress={onChangeDestination}><Text style={s.link}>Change</Text></Pressable> : null}</View>
    <View style={s.sectionHead}><Text style={s.sectionTitle}>RIDERS</Text><View style={s.count}><Text style={s.countText}>{group.members.length}</Text></View></View>
    <View style={s.list}>{group.members.map((member, index) => { const isHost = member.id === group.hostId; return <View key={member.id} style={[s.memberRow, index < group.members.length - 1 && s.divider]}><Initials member={member} /><View style={{ flex: 1, marginLeft: 12 }}><Text style={s.memberName}>{member.name}{member.id === participantId ? ' (you)' : ''}</Text><Text style={s.meta}>{isHost ? 'Host' : 'Ready to ride'}</Text></View>{host && !isHost ? <Pressable accessibilityLabel={`Remove ${member.name}`} onPress={() => onRemove(member.id)} style={s.remove}><Ionicons name="close" size={18} color={C.red} /></Pressable> : <View style={s.ready}><Ionicons name="checkmark" size={13} color={C.white} /></View>}</View>; })}</View>
    {group.members.length === 1 ? <Text style={s.emptyHint}>You’re the first one here. Share the code so your friends can join.</Text> : null}{error ? <View style={s.error}><Text style={s.errorText}>{error}</Text></View> : null}
  </ScrollView><View style={s.sticky}>{host ? <Button disabled={busy} label={busy ? 'Starting ride…' : 'Start Ride'} icon="arrow-forward" onPress={onStart} /> : <View style={s.waiting}><ActivityIndicator color={C.ink} /><Text style={s.waitingText}>Waiting for the host to start…</Text></View>}<Pressable onPress={onLeave}><Text style={s.leaveLink}>{host ? 'Cancel group' : 'Leave group'}</Text></Pressable></View></SafeAreaView>;
}

function ActiveRide({ group, participantId, profile, online, reconnecting, onLeave, onEnd, onStats }: { group: ApiGroup; participantId: string; profile: Profile; online: boolean; reconnecting: boolean; onLeave: () => void; onEnd: (distance: number) => void; onStats: (distance: number, maxSpeed: number) => void }) {
  const [now, setNow] = useState(Date.now()); const [voice, setVoice] = useState(profile.voiceEnabled); const [cheerOpen, setCheerOpen] = useState(false); const [toast, setToast] = useState(''); const [locationError, setLocationError] = useState(''); const [distance, setDistance] = useState(0); const [maxSpeed, setMaxSpeed] = useState(0); const [currentSpeed, setCurrentSpeed] = useState(0); const [follow, setFollow] = useState(true); const [fitKey, setFitKey] = useState(0);
  const seen = useRef(new Set(group.cheers.map((item) => item.id))); const queue = useRef<{ sender: string; message: string }[]>([]); const speaking = useRef(false); const previousPoint = useRef<{ latitude: number; longitude: number; timestamp: number } | null>(null);
  const host = group.hostId === participantId; const elapsed = elapsedSeconds(group.startedAt, now); const avg = elapsed ? distance / (elapsed / 3600) : 0;
  const mappable = group.members.filter((m): m is ApiMember & { latitude: number; longitude: number } => m.latitude != null && m.longitude != null);
  const playNext = () => { const next = queue.current.shift(); if (!next) { speaking.current = false; return; } speaking.current = true; setToast(`${next.sender}: ${next.message}`); if (voice) Speech.speak(`${next.sender} says ${next.message}`, { language: 'en-SG', onDone: playNext, onStopped: playNext, onError: playNext }); else setTimeout(playNext, 1800); };
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { storage.rideStats(group.code).then((stats) => { setDistance(stats.distanceKm); setMaxSpeed(stats.maxSpeedKmh); }); }, [group.code]);
  useEffect(() => { const timer = setInterval(async () => { const stats = await storage.rideStats(group.code); setDistance(stats.distanceKm); setMaxSpeed(stats.maxSpeedKmh); onStats(stats.distanceKm, stats.maxSpeedKmh); }, 3000); return () => clearInterval(timer); }, [group.code]);
  useEffect(() => {
    let watcher: Location.LocationSubscription | undefined; let demoTimer: ReturnType<typeof setInterval> | undefined; let cancelled = false;
    (async () => { if (__DEV__ && profile.demoMode) { setLocationError(''); setToast('Development demo location active'); let step = 0; demoTimer = setInterval(async () => { step += 1; const latitude = 1.2903 + Math.sin(step / 5) * 0.003; const longitude = 103.852 + step * 0.00025; const speed = 22; const stats = await storage.rideStats(group.code); const nextStats = { ...stats, distanceKm: stats.distanceKm + 0.025, maxSpeedKmh: Math.max(stats.maxSpeedKmh, speed), lastCoordinate: { latitude, longitude, timestamp: Date.now() } }; await storage.saveRideStats(nextStats); setDistance(nextStats.distanceKm); setCurrentSpeed(speed); setMaxSpeed(nextStats.maxSpeedKmh); await groupApi.updateLocation(group.code, participantId, { latitude, longitude, accuracy: 5 }, `${speed.toFixed(1)} km/h`, speed / 3.6).catch(() => undefined); }, 2500); return; } const permission = await Location.getForegroundPermissionsAsync(); if (permission.status !== 'granted') { setLocationError('Location access is required so riders can see you.'); return; }
      setLocationError(''); const backgroundOwnsStats = await startBackgroundTracking().catch(() => false);
      watcher = await Location.watchPositionAsync({ accuracy: Location.Accuracy.High, distanceInterval: 8, timeInterval: 4000 }, async (update) => { if (cancelled) return; const speed = Math.max(0, Math.min(75, (update.coords.speed || 0) * 3.6)); const point = { latitude: update.coords.latitude, longitude: update.coords.longitude, timestamp: update.timestamp }; const stats = await storage.rideStats(group.code); const moved = !backgroundOwnsStats && previousPoint.current ? acceptedMovement(previousPoint.current, point, update.coords.accuracy) : 0; previousPoint.current = point; const nextStats = { ...stats, distanceKm: stats.distanceKm + moved, maxSpeedKmh: Math.max(stats.maxSpeedKmh, speed), lastCoordinate: point }; await storage.saveRideStats(nextStats); setDistance(nextStats.distanceKm); setCurrentSpeed(speed); setMaxSpeed(nextStats.maxSpeedKmh); await groupApi.updateLocation(group.code, participantId, { latitude: update.coords.latitude, longitude: update.coords.longitude, accuracy: update.coords.accuracy }, `${speed.toFixed(1)} km/h`, update.coords.speed || 0).catch(() => undefined); });
    })(); return () => { cancelled = true; if (demoTimer) clearInterval(demoTimer); watcher?.remove(); };
  }, [group.code, participantId, profile.demoMode]);
  useEffect(() => { for (const cheer of group.cheers) if (!seen.current.has(cheer.id)) { seen.current.add(cheer.id); if (cheer.senderId !== participantId) queue.current.push({ sender: cheer.senderName, message: cheer.message }); } if (!speaking.current && queue.current.length) playNext(); }, [group.cheers, participantId, voice]);
  useEffect(() => () => { Speech.stop(); }, []);
  const sendCheer = async (message: string) => { setCheerOpen(false); try { await groupApi.cheer(group.code, participantId, message); setToast(`Sent: ${message}`); } catch { setToast('Cheer not sent. Check your connection.'); } };
  return <View style={s.fill}><StatusBar style="dark" /><GroupMap members={mappable.map((m) => ({ ...m, isYou: m.id === participantId }))} destination={{ ...group.destination, latitude: group.destination.latitude || 1.28, longitude: group.destination.longitude || 103.87 }} follow={follow} fitKey={fitKey} onGesture={() => setFollow(false)} />
    <SafeAreaView style={s.rideOverlay} pointerEvents="box-none"><View><View style={s.rideHeader}><Pressable accessibilityRole="button" accessibilityLabel={host ? 'End Ride' : 'Leave Ride'} onPress={host ? () => onEnd(distance) : onLeave} style={s.mapButton}><Ionicons name="close" size={22} color={C.ink} /></Pressable><View style={s.liveBadge}><View style={s.liveDot} /><Text style={s.liveText}>{group.code} · LIVE</Text></View><Pressable accessibilityRole="button" accessibilityLabel={voice ? 'Mute voice cheers' : 'Enable voice cheers'} onPress={() => { const next = !voice; setVoice(next); storage.saveProfile({ ...profile, voiceEnabled: next }); if (voice) Speech.stop(); }} style={[s.mapButton, voice && { backgroundColor: C.ink }]}><Ionicons name={voice ? 'headset' : 'headset-outline'} size={21} color={voice ? C.white : C.ink} /></Pressable></View><NetworkPill online={online} connecting={reconnecting} />{toast ? <View style={s.toast}><Ionicons name="volume-high" size={18} color={C.ink} /><Text style={s.toastText}>{toast}</Text><Pressable onPress={() => setToast('')}><Ionicons name="close" size={16} color={C.soft} /></Pressable></View> : null}</View>
      <View style={s.mapTools}><Pressable onPress={() => setFollow(true)} style={[s.mapTool, follow && s.mapToolActive]}><Ionicons name="locate" size={19} color={C.ink} /><Text style={s.mapToolText}>Recenter</Text></Pressable><Pressable onPress={() => { setFollow(false); setFitKey((key) => key + 1); }} style={s.mapTool}><Ionicons name="people" size={19} color={C.ink} /><Text style={s.mapToolText}>Group</Text></Pressable></View>
      <View style={s.rideBottom}>{locationError ? <View style={s.permissionCard}><Ionicons name="location-outline" size={22} color={C.red} /><View style={{ flex: 1 }}><Text style={s.memberName}>Location needed</Text><Text style={s.meta}>{locationError}</Text></View><Pressable onPress={async () => { const result = await requestRideLocation(); if (result.foreground.status === 'granted') setLocationError(''); else if (!result.foreground.canAskAgain) Linking.openSettings(); }}><Text style={s.link}>Fix</Text></Pressable></View> : null}
        <View style={s.destinationStrip}><Ionicons name="flag" size={20} color={C.white} /><View style={{ flex: 1 }}><Text style={s.codeEyebrow}>DESTINATION</Text><Text style={s.destinationStripText}>{group.destination.name}</Text></View><Text style={s.riderCount}>{group.members.length} riders</Text></View>
        <View style={s.stats}><Stat label="TIME" value={formatDuration(elapsed)} /><Stat label="DISTANCE" value={distanceText(distance, profile.units)} /><Stat label="SPEED" value={speedText(currentSpeed, profile.units)} /><Stat label="AVERAGE" value={speedText(avg, profile.units)} /></View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.riderStrip}>{group.members.map((member) => { const f = freshness(member.lastSeen, now); return <View key={member.id} style={s.riderChip}><View style={[s.statusDot, { backgroundColor: f.state === 'live' ? '#59B87C' : f.state === 'delayed' ? '#E4A83A' : '#9CA7A2' }]} /><Text style={s.riderChipName}>{member.name}</Text><Text style={s.riderChipStatus}>{f.label}</Text></View>; })}</ScrollView>
        <Button label="Cheer" icon="megaphone" onPress={() => setCheerOpen(true)} />
      </View></SafeAreaView>
    <Modal visible={cheerOpen} transparent animationType="slide" onRequestClose={() => setCheerOpen(false)}><Pressable style={s.backdrop} onPress={() => setCheerOpen(false)} /><SafeAreaView style={s.sheet}><View style={s.sheetHandle} /><Text style={s.pageTitle}>Quick cheer</Text><Text style={s.body}>One tap sends a spoken message to the group.</Text><View style={s.cheerGrid}>{CHEERS.map((cheer) => <Pressable key={cheer} onPress={() => sendCheer(cheer)} style={s.cheer}><Ionicons name="volume-high" size={18} color={C.ink} /><Text style={s.cheerText}>{cheer}</Text></Pressable>)}</View></SafeAreaView></Modal>
  </View>;
}
function Stat({ label, value }: { label: string; value: string }) { return <View style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text></View>; }

function Summary({ summary, units, onDone }: { summary: RideSummary; units: Profile['units']; onDone: () => void }) { return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={[s.content, { flexGrow: 1 }]}><View style={s.summaryHero}><View style={s.finishIcon}><Ionicons name="flag" size={34} color={C.ink} /></View><Text style={s.kicker}>RIDE COMPLETE</Text><Text style={s.bigTitle}>Finished together.</Text><Text style={s.body}>{summary.destination.name} · {new Date(summary.endedAt).toLocaleDateString()}</Text></View><View style={s.summaryStats}><Stat label="DURATION" value={formatDuration(summary.durationSeconds)} /><Stat label="DISTANCE" value={distanceText(summary.distanceKm, units)} /><Stat label="AVG SPEED" value={speedText(summary.averageSpeedKmh, units)} /><Stat label="RIDERS" value={String(summary.riders.length)} /></View><Text style={s.sectionTitle}>YOUR KAKI</Text><View style={s.avatarStack}>{summary.riders.map((rider) => <Initials key={rider.id} member={rider as ApiMember} size={50} />)}</View></ScrollView><View style={s.sticky}><Button label="Done" icon="arrow-forward" onPress={onDone} /></View></SafeAreaView>; }
function SummaryRow({ ride, units, onPress }: { ride: RideSummary; units: Profile['units']; onPress: () => void }) { return <Pressable onPress={onPress} style={s.summaryRow}><View style={s.activeIcon}><Ionicons name="bicycle" size={21} color={C.white} /></View><View style={{ flex: 1 }}><Text style={s.memberName}>{ride.destination.name}</Text><Text style={s.meta}>{new Date(ride.endedAt).toLocaleDateString()} · {distanceText(ride.distanceKm, units, 1)} · {formatDuration(ride.durationSeconds)}</Text></View><Ionicons name="chevron-forward" size={19} color={C.soft} /></Pressable>; }
function History({ history, units, onBack, onOpen }: { history: RideSummary[]; units: Profile['units']; onBack: () => void; onOpen: (ride: RideSummary) => void }) { return <SafeAreaView style={s.screen}><Header title="RIDE HISTORY" onBack={onBack} /><ScrollView contentContainerStyle={s.content}>{history.map((ride) => <SummaryRow key={ride.code} units={units} ride={ride} onPress={() => onOpen(ride)} />)}</ScrollView></SafeAreaView>; }
function Settings({ profile, permission, onBack, onSave }: { profile: Profile; permission: string; onBack: () => void; onSave: (profile: Profile) => void }) { const [draft, setDraft] = useState(profile); return <SafeAreaView style={s.screen}><Header title="SETTINGS" onBack={onBack} /><ScrollView contentContainerStyle={s.content}><Field label="DISPLAY NAME"><TextInput value={draft.displayName} onChangeText={(displayName) => setDraft({ ...draft, displayName })} style={s.input} placeholder="Your name" /></Field><Setting label="Voice cheers" detail="Play incoming cheers automatically"><Switch value={draft.voiceEnabled} onValueChange={(voiceEnabled) => setDraft({ ...draft, voiceEnabled })} trackColor={{ true: C.ink }} /></Setting><Setting label="Units" detail={draft.units === 'metric' ? 'Kilometres and km/h' : 'Miles and mph'}><Pressable onPress={() => setDraft({ ...draft, units: draft.units === 'metric' ? 'imperial' : 'metric' })}><Text style={s.link}>{draft.units === 'metric' ? 'Metric' : 'Imperial'}</Text></Pressable></Setting><Setting label="Location permission" detail={permission}><Pressable onPress={() => Linking.openSettings()}><Text style={s.link}>Settings</Text></Pressable></Setting>{__DEV__ ? <Setting label="Demo mode" detail="Development only · simulated location"><Switch value={draft.demoMode} onValueChange={(demoMode) => setDraft({ ...draft, demoMode })} /></Setting> : null}<View style={s.about}><Logo /><Text style={s.meta}>Paladin v1.0 · Built for riding together.</Text></View></ScrollView><View style={s.sticky}><Button label="Save Settings" onPress={() => onSave({ ...draft, displayName: draft.displayName.trim() })} /></View></SafeAreaView>; }
function Setting({ label, detail, children }: { label: string; detail: string; children: React.ReactNode }) { return <View style={s.setting}><View style={{ flex: 1 }}><Text style={s.memberName}>{label}</Text><Text style={s.meta}>{detail}</Text></View>{children}</View>; }

export default function App() {
  const [screen, setScreen] = useState<Screen>('boot'); const [mode, setMode] = useState<Mode>('create'); const [profile, setProfile] = useState(EMPTY_PROFILE); const [group, setGroup] = useState<ApiGroup | null>(null); const [participantId, setParticipantId] = useState(''); const [history, setHistory] = useState<RideSummary[]>([]); const [summary, setSummary] = useState<RideSummary | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [online, setOnline] = useState(true); const [reconnecting, setReconnecting] = useState(false); const [permission, setPermission] = useState('Not requested'); const distanceRef = useRef(0); const restoreStarted = useRef(false);
  const finishLocally = async (rideSummary: RideSummary) => { await storage.addHistory(rideSummary); await storage.clearSession(); await storage.clearRideStats(); await stopBackgroundTracking().catch(() => undefined); setHistory(await storage.history()); setGroup(null); setParticipantId(''); setSummary(rideSummary); setScreen('summary'); };
  const restore = async () => { const [hasOnboarded, savedProfile, savedSession, savedHistory] = await Promise.all([storage.hasOnboarded(), storage.profile(), storage.session(), storage.history()]); setProfile(savedProfile); setHistory(savedHistory); const status = await locationPermissionStatus().catch(() => null); if (status) setPermission(status.foreground.status === 'granted' ? (status.background?.status === 'granted' ? 'Always allowed' : 'While using app') : 'Not allowed');
    if (!hasOnboarded) return setScreen('onboarding'); if (!savedSession) return setScreen('home'); setReconnecting(true); try { const result = await groupApi.resume(savedSession.code, savedProfile.deviceId); setGroup(result.group); setParticipantId(result.participantId); await storage.saveSession({ code: result.group.code, participantId: result.participantId, group: result.group }); if (result.group.status === 'ended' && result.group.summary) await finishLocally(result.group.summary); else setScreen(result.group.status === 'active' ? 'active' : 'lobby'); } catch { if (savedSession.group && savedSession.group.status !== 'ended') { setGroup(savedSession.group); setParticipantId(savedSession.participantId); setScreen(savedSession.group.status === 'active' ? 'active' : 'lobby'); } else { setScreen('home'); } } finally { setReconnecting(false); } };
  useEffect(() => { if (!restoreStarted.current) { restoreStarted.current = true; restore(); } const unsubscribe = NetInfo.addEventListener((state) => setOnline(Boolean(state.isConnected && state.isInternetReachable !== false))); return unsubscribe; }, []);
  const refresh = async () => { if (!group) return; try { if (participantId) await groupApi.heartbeat(group.code, participantId); const result = await groupApi.snapshot(group.code); setGroup(result.group); await storage.saveSession({ code: result.group.code, participantId, group: result.group }); setReconnecting(false); if (result.group.status === 'ended' && result.group.summary) await finishLocally(result.group.summary); else if (result.group.status === 'active' && screen === 'lobby') setScreen('active'); } catch { setReconnecting(true); } };
  useEffect(() => { const app = AppState.addEventListener('change', (state) => { if (state === 'active' && group) refresh(); }); return () => app.remove(); }, [group?.code, participantId, screen]);
  useEffect(() => { if (!group || !['lobby', 'active'].includes(screen)) return; const timer = setInterval(refresh, screen === 'active' ? 2500 : 1800); refresh(); return () => clearInterval(timer); }, [group?.code, screen]);
  const submit = async (data: { name: string; code: string; rideName: string; groupName: string; destination: Destination }) => { if (busy) return; setBusy(true); setError(''); try { const result = mode === 'create' ? await groupApi.create({ name: data.name, deviceId: profile.deviceId, activity: 'ride', rideName: data.rideName, groupName: data.groupName, destination: data.destination }) : await groupApi.join(data.code, data.name, profile.deviceId); const updated = { ...profile, displayName: data.name }; await storage.saveProfile(updated); await storage.saveSession({ code: result.group.code, participantId: result.participantId, group: result.group }); setProfile(updated); setGroup(result.group); setParticipantId(result.participantId); setScreen(result.group.status === 'active' ? 'active' : 'lobby'); } catch (e) { setError(e instanceof ApiError ? e.message : 'Paladin could not complete that action.'); } finally { setBusy(false); } };
  const start = async () => { if (!group || busy) return; setBusy(true); setError(''); try { const result = await groupApi.start(group.code, participantId); setGroup(result.group); await storage.saveRideStats({ code: group.code, distanceKm: 0, maxSpeedKmh: 0 }); await startBackgroundTracking().catch(() => false); setScreen('active'); } catch (e) { setError(e instanceof Error ? e.message : 'The ride could not start.'); } finally { setBusy(false); } };
  const leave = () => { if (!group) return; const host = group.hostId === participantId; Alert.alert(host ? 'Cancel this group?' : 'Leave this group?', host ? 'The next rider will become host. If nobody else is here, the group will close.' : 'You will leave the lobby.', [{ text: 'Stay', style: 'cancel' }, { text: host ? 'Cancel / Leave' : 'Leave', style: 'destructive', onPress: async () => { await groupApi.leave(group.code, participantId).catch(() => undefined); await storage.clearSession(); setGroup(null); setScreen('home'); } }]); };
  const leaveActive = () => { if (!group) return; Alert.alert('Leave this ride?', 'Your location will stop being shared with the group.', [{ text: 'Keep riding', style: 'cancel' }, { text: 'Leave Ride', style: 'destructive', onPress: async () => { await groupApi.leave(group.code, participantId).catch(() => undefined); await stopBackgroundTracking().catch(() => undefined); await storage.clearSession(); setGroup(null); setScreen('home'); } }]); };
  const end = (distance: number) => { if (!group) return; Alert.alert('End ride for everyone?', 'All riders will stop sharing location and receive the ride summary.', [{ text: 'Keep riding', style: 'cancel' }, { text: 'End Ride', style: 'destructive', onPress: async () => { if (busy) return; setBusy(true); try { const result = await groupApi.end(group.code, participantId, distance); if (result.group.summary) await finishLocally(result.group.summary); } finally { setBusy(false); } } }]); };
  const remove = (id: string) => { if (!group) return; const member = group.members.find((item) => item.id === id); Alert.alert(`Remove ${member?.name || 'rider'}?`, 'They can rejoin while the ride is still in the lobby.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: async () => { const result = await groupApi.leave(group.code, participantId, id); setGroup(result.group); } }]); };
  const changeDestination = () => { if (!group) return; const currentIndex = DESTINATIONS.findIndex((item) => item.name === group.destination.name); const next = DESTINATIONS[(currentIndex + 1 + DESTINATIONS.length) % DESTINATIONS.length]; Alert.alert('Change destination?', `Set destination to ${next.name}?`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Change', onPress: async () => { const result = await groupApi.destination(group.code, participantId, next); setGroup(result.group); } }]); };
  if (screen === 'boot') return <View style={[s.fill, s.center]}><Logo /><ActivityIndicator color={C.ink} style={{ marginTop: 24 }} /><Text style={[s.meta, { marginTop: 10 }]}>Restoring Paladin…</Text></View>;
  if (screen === 'onboarding') return <Onboarding onDone={async () => { await storage.completeOnboarding(); setScreen('home'); }} />;
  if (screen === 'home') return <><StatusBar style="dark" /><Home profile={profile} active={group?.status === 'active' ? group : null} history={history} onCreate={() => { setMode('create'); setError(''); setScreen('setup'); }} onJoin={() => { setMode('join'); setError(''); setScreen('setup'); }} onResume={() => setScreen('active')} onSettings={() => setScreen('settings')} onHistory={() => setScreen('history')} onOpenRide={(ride) => { setSummary(ride); setScreen('summary'); }} /></>;
  if (screen === 'setup') return <Setup mode={mode} profile={profile} busy={busy} error={error} onBack={() => setScreen('home')} onSubmit={submit} />;
  if (screen === 'lobby' && group) return <Lobby group={group} participantId={participantId} busy={busy} error={error} onStart={start} onLeave={leave} onChangeDestination={changeDestination} onRemove={remove} />;
  if (screen === 'active' && group) return <ActiveRide group={group} participantId={participantId} profile={profile} online={online} reconnecting={reconnecting} onLeave={leaveActive} onEnd={end} onStats={(distance) => { distanceRef.current = distance; }} />;
  if (screen === 'summary' && summary) return <Summary summary={summary} units={profile.units} onDone={() => { setSummary(null); setScreen('home'); }} />;
  if (screen === 'history') return <History history={history} units={profile.units} onBack={() => setScreen('home')} onOpen={(ride) => { setSummary(ride); setScreen('summary'); }} />;
  if (screen === 'settings') return <Settings profile={profile} permission={permission} onBack={() => setScreen('home')} onSave={async (value) => { await storage.saveProfile(value); setProfile(value); setScreen('home'); }} />;
  return null;
}

const s = StyleSheet.create({
  fill: { flex: 1 }, center: { alignItems: 'center', justifyContent: 'center', backgroundColor: C.cream }, screen: { flex: 1, backgroundColor: C.cream }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] }, disabled: { opacity: 0.45 },
  button: { minHeight: 58, borderRadius: 29, backgroundColor: C.orange, paddingHorizontal: 22, flexDirection: 'row', gap: 10, alignItems: 'center', justifyContent: 'center' }, buttonSecondary: { backgroundColor: C.paper, borderWidth: 1, borderColor: C.line }, buttonDanger: { backgroundColor: C.red }, buttonText: { color: C.white, fontSize: 16, fontWeight: '800' }, buttonTextSecondary: { color: C.ink },
  header: { minHeight: 66, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerTitle: { fontSize: 11, fontWeight: '900', color: C.ink, letterSpacing: 1.5 }, iconButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  logo: { flexDirection: 'row', alignItems: 'center', gap: 9 }, logoMark: { width: 34, height: 34, borderRadius: 17, backgroundColor: C.ink, overflow: 'hidden' }, logoDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.lime, position: 'absolute', top: 8, right: 8 }, logoTrail: { width: 24, height: 4, borderRadius: 2, backgroundColor: C.orange, position: 'absolute', bottom: 8, left: 4, transform: [{ rotate: '-35deg' }] }, logoText: { color: C.ink, fontWeight: '900', letterSpacing: 1.3, fontSize: 15 },
  onboarding: { flex: 1, padding: 24, paddingTop: 34, justifyContent: 'space-between' }, onboardHero: { alignItems: 'flex-start' }, onboardIcon: { width: 92, height: 92, borderRadius: 31, backgroundColor: C.lime, alignItems: 'center', justifyContent: 'center', marginBottom: 32 }, kicker: { color: C.orange, fontSize: 10, fontWeight: '900', letterSpacing: 1.6, marginBottom: 9 }, bigTitle: { color: C.ink, fontSize: 42, lineHeight: 44, fontWeight: '900', letterSpacing: -1.5 }, body: { color: C.soft, fontSize: 15, lineHeight: 22, marginTop: 13 }, dots: { flexDirection: 'row', justifyContent: 'center', gap: 7, marginBottom: 20 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.line }, dotActive: { width: 24, backgroundColor: C.orange }, skip: { color: C.soft, fontWeight: '700', textAlign: 'center', padding: 14 },
  home: { paddingHorizontal: 24, paddingBottom: 30, gap: 28 }, homeHeader: { paddingTop: Platform.OS === 'android' ? 22 : 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, heroTitle: { color: C.ink, fontSize: 44, lineHeight: 46, fontWeight: '900', letterSpacing: -1.8 }, activeCard: { borderRadius: 22, backgroundColor: C.lime, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 13 }, activeIcon: { width: 47, height: 47, borderRadius: 15, backgroundColor: C.orange, alignItems: 'center', justifyContent: 'center' }, cardTitle: { color: C.ink, fontSize: 17, fontWeight: '800' }, meta: { color: C.soft, fontSize: 11, lineHeight: 16, marginTop: 3 },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }, sectionTitle: { color: C.ink, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, link: { color: C.orange, fontSize: 12, fontWeight: '800' }, empty: { backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 20, alignItems: 'center', padding: 24 }, emptyTitle: { color: C.ink, fontSize: 15, fontWeight: '800', marginTop: 8 },
  content: { padding: 24, paddingBottom: 125 }, pageTitle: { color: C.ink, fontSize: 36, lineHeight: 39, fontWeight: '900', letterSpacing: -1.2 }, fieldLabel: { color: C.ink, fontSize: 10, fontWeight: '900', letterSpacing: 1.4, marginBottom: 9 }, input: { height: 58, borderRadius: 17, borderWidth: 1, borderColor: C.line, backgroundColor: C.paper, paddingHorizontal: 16, color: C.ink, fontSize: 16, fontWeight: '600' }, codeInput: { textAlign: 'center', letterSpacing: 7, fontSize: 23, fontWeight: '900' }, destination: { width: 180, minHeight: 132, padding: 15, borderRadius: 20, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, gap: 8 }, destinationActive: { backgroundColor: C.ink, borderColor: C.ink }, destinationName: { color: C.ink, fontWeight: '800', fontSize: 15 }, error: { marginTop: 20, padding: 13, borderRadius: 14, backgroundColor: '#FCE5DE', flexDirection: 'row', alignItems: 'center', gap: 9 }, errorText: { flex: 1, color: C.red, fontSize: 12, lineHeight: 17 }, sticky: { paddingHorizontal: 24, paddingTop: 12, paddingBottom: Platform.OS === 'android' ? 22 : 12, backgroundColor: C.cream, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: C.line },
  codeCard: { backgroundColor: C.ink, borderRadius: 25, padding: 22 }, codeEyebrow: { color: C.mint, fontSize: 9, fontWeight: '900', letterSpacing: 1.5 }, groupCode: { color: C.white, fontSize: 42, letterSpacing: 8, fontWeight: '900', textAlign: 'center', marginVertical: 16 }, shareRow: { flexDirection: 'row', gap: 10 }, smallAction: { flex: 1, height: 44, borderRadius: 14, backgroundColor: C.lime, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, smallActionText: { color: C.ink, fontSize: 12, fontWeight: '800' }, planCard: { marginTop: 15, padding: 15, borderRadius: 20, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center', gap: 12 }, count: { width: 24, height: 24, borderRadius: 12, backgroundColor: C.mint, alignItems: 'center', justifyContent: 'center' }, countText: { color: C.ink, fontSize: 11, fontWeight: '900' }, list: { borderRadius: 20, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, paddingHorizontal: 15 }, memberRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13 }, divider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line }, memberName: { color: C.ink, fontSize: 14, fontWeight: '800' }, avatar: { alignItems: 'center', justifyContent: 'center' }, avatarText: { color: C.white, fontWeight: '900', fontSize: 13 }, ready: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#59B87C', alignItems: 'center', justifyContent: 'center' }, remove: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#FCE5DE', alignItems: 'center', justifyContent: 'center' }, emptyHint: { color: C.soft, fontSize: 12, textAlign: 'center', marginTop: 14 }, waiting: { height: 58, borderRadius: 29, backgroundColor: C.mint, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }, waitingText: { color: C.ink, fontWeight: '800' }, leaveLink: { color: C.red, fontWeight: '700', fontSize: 12, textAlign: 'center', paddingTop: 13 },
  rideOverlay: { flex: 1, justifyContent: 'space-between' }, rideHeader: { paddingHorizontal: 18, paddingTop: Platform.OS === 'android' ? 18 : 6, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, mapButton: { width: 45, height: 45, borderRadius: 23, backgroundColor: C.paper, alignItems: 'center', justifyContent: 'center' }, liveBadge: { backgroundColor: C.ink, borderRadius: 20, paddingHorizontal: 13, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 6 }, liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.orange }, liveText: { color: C.white, fontWeight: '900', fontSize: 10, letterSpacing: 1 }, networkPill: { alignSelf: 'center', marginTop: 8, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 14, backgroundColor: C.lime, flexDirection: 'row', alignItems: 'center', gap: 7 }, networkText: { color: C.ink, fontWeight: '800', fontSize: 11 }, toast: { marginHorizontal: 18, marginTop: 8, backgroundColor: C.lime, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9 }, toastText: { flex: 1, color: C.ink, fontSize: 12, fontWeight: '700' }, mapTools: { position: 'absolute', right: 16, top: 130, gap: 8 }, mapTool: { backgroundColor: C.paper, borderRadius: 17, paddingHorizontal: 11, paddingVertical: 9, alignItems: 'center' }, mapToolActive: { backgroundColor: C.lime }, mapToolText: { color: C.ink, fontSize: 8, fontWeight: '800', marginTop: 2 },
  rideBottom: { paddingHorizontal: 14, paddingBottom: Platform.OS === 'android' ? 16 : 5, gap: 8 }, permissionCard: { backgroundColor: '#FCE5DE', borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9 }, destinationStrip: { backgroundColor: C.ink, borderRadius: 18, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, destinationStripText: { color: C.white, fontWeight: '800', fontSize: 14 }, riderCount: { color: C.mint, fontSize: 11, fontWeight: '800' }, stats: { backgroundColor: C.paper, borderRadius: 20, padding: 13, flexDirection: 'row', flexWrap: 'wrap' }, stat: { width: '50%', paddingVertical: 8, paddingHorizontal: 9 }, statLabel: { color: C.soft, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, statValue: { color: C.ink, fontSize: 17, fontWeight: '900', marginTop: 3 }, riderStrip: { gap: 7 }, riderChip: { minWidth: 140, backgroundColor: C.paper, borderRadius: 14, padding: 9 }, statusDot: { width: 7, height: 7, borderRadius: 4, position: 'absolute', right: 9, top: 9 }, riderChipName: { color: C.ink, fontSize: 11, fontWeight: '800' }, riderChipStatus: { color: C.soft, fontSize: 8, marginTop: 2 }, backdrop: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(24,53,44,0.35)' }, sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, backgroundColor: C.cream, padding: 24, paddingBottom: 30, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, sheetHandle: { width: 42, height: 5, borderRadius: 3, backgroundColor: C.line, alignSelf: 'center', marginBottom: 20 }, cheerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 20 }, cheer: { width: '48%', minHeight: 58, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }, cheerText: { flex: 1, color: C.ink, fontSize: 12, fontWeight: '800' },
  summaryHero: { alignItems: 'center', marginTop: 24, marginBottom: 30 }, finishIcon: { width: 82, height: 82, borderRadius: 28, backgroundColor: C.lime, alignItems: 'center', justifyContent: 'center', marginBottom: 20 }, summaryStats: { backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 22, flexDirection: 'row', flexWrap: 'wrap', marginBottom: 28 }, avatarStack: { flexDirection: 'row', gap: 8, marginTop: 12 }, summaryRow: { padding: 13, borderRadius: 18, backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 9 }, setting: { minHeight: 72, backgroundColor: C.paper, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 }, about: { alignItems: 'center', marginTop: 42, gap: 9 },
});
